### ISSUE TITLE
Usage tutorial

### ISSUE THREAD

**Issue by wolololo** [huig-/TFG#1]

**Comment by huig-** [comment]
Right now we are working on the code, it is not finished yet. In about a month it will be finished and then we'll provide a tutorial. The code here is not up to date also. Also, why are you interested in this? What are you trying to do?

**Comment by wolololo** [comment]
Thanks for sharing this information, so I was wondering: Defense against DDoS in Tor

**Comment by huig-** [comment]
The idea is to detect DDoS attacks in the Tor network
